# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{content_scrapper}
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gyorgy Frivolt"]
  s.date = %q{2010-02-28}
  s.description = %q{If you want to cut only the content of pages, without any other part (like the menu, header, footer, commercials, etc.), you might find this gem very handy. A DSL is also defined for nifty definitions for your screen scrapping and sanitization.}
  s.email = %q{gyorgy.frivolt@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".specification",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "config/content_scrapper.rb",
     "content_scrapper.gemspec",
     "lib/content_scrapper.rb",
     "lib/content_scrapper/content_mapping.rb",
     "lib/content_scrapper/feedzirra.rb",
     "rails/init.rb",
     "test/helper.rb",
     "test/test_content_mapping.rb",
     "test/test_content_scrapper.rb",
     "test/test_pages/encoding.html",
     "test/test_pages/pretty.html",
     "test/test_pages/twocontent.html",
     "test/test_pages/ugly.html"
  ]
  s.homepage = %q{http://github.com/fifigyuri/content_scrapper}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Gem for those who want to screen scrap only the content part of web pages, blogs or articles.}
  s.test_files = [
    "test/test_content_mapping.rb",
     "test/test_content_scrapper.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 2.10.2"])
      s.add_development_dependency(%q<mocha>, [">= 0.9.8"])
      s.add_runtime_dependency(%q<sanitize>, [">= 1.2.0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4.1"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 2.10.2"])
      s.add_dependency(%q<mocha>, [">= 0.9.8"])
      s.add_dependency(%q<sanitize>, [">= 1.2.0"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.1"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 2.10.2"])
    s.add_dependency(%q<mocha>, [">= 0.9.8"])
    s.add_dependency(%q<sanitize>, [">= 1.2.0"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.1"])
  end
end

